apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g9g6x32nr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g9g6x32nr-python 
  name: g9g6x32nr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g9g6x32nr-python 
